#version: '3.8'
services:
  db:
    container_name: owlreads-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: owlreads_admin
      POSTGRES_PASSWORD: D83xCEchx2C6YaU
      POSTGRES_DB: owlreads_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  pgadmin:
    container_name: owlreads-pgadmin
    image: dpage/pgadmin4:7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: malinetskaya2004@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Owm20ILFJZkaAn4
    ports:
      - "8080:80"

volumes:
  pgdata:
